--ADDRESS Table---------------------------------------------------------------------------------------------------------------
CREATE TABLE ADDRESS 
(
  ADDRESS_ID NUMBER NOT NULL 
, STREET_NUMBER VARCHAR2(10 BYTE) 
, STREET_NAME VARCHAR2(200 BYTE) 
, CITY VARCHAR2(100 BYTE) 
, COUNTRY_ID NUMBER 
, CONSTRAINT PK_ADDRESS PRIMARY KEY 
  (
    ADDRESS_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_ADDRESS ON ADDRESS (ADDRESS_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE ADDRESS
ADD CONSTRAINT FK_ADDR_CTRY FOREIGN KEY
(
  COUNTRY_ID 
)
REFERENCES COUNTRY
(
  COUNTRY_ID 
)
ENABLE;


--ADDRESS_STATUS Table---------------------------------------------------------------------------------------------------------------
CREATE TABLE ADDRESS_STATUS 
(
  STATUS_ID NUMBER NOT NULL 
, ADDRESS_STATUS VARCHAR2(30 BYTE) 
, CONSTRAINT PK_ADDR_STATUS PRIMARY KEY 
  (
    STATUS_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_ADDR_STATUS ON ADDRESS_STATUS (STATUS_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

--AUTHOR Table---------------------------------------------------------------------------------------------------------------
CREATE TABLE AUTHOR 
(
  AUTHOR_ID NUMBER NOT NULL 
, AUTHOR_NAME VARCHAR2(400 BYTE) 
, CONSTRAINT PK_AUTHOR PRIMARY KEY 
  (
    AUTHOR_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_AUTHOR ON AUTHOR (AUTHOR_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

--BOOK Table---------------------------------------------------------------------------------------------------------------
CREATE TABLE BOOK 
(
  BOOK_ID NUMBER NOT NULL 
, TITLE VARCHAR2(255 BYTE) 
, ISBN13 VARCHAR2(13 BYTE) 
, LANGUAGE_ID NUMBER 
, NUM_PAGES NUMBER 
, PUBLICATION_DATE DATE 
, PUBLISHER_ID NUMBER 
, CONSTRAINT PK_BOOK PRIMARY KEY 
  (
    BOOK_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_BOOK ON BOOK (BOOK_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE BOOK
ADD CONSTRAINT FK_BOOK_LANG FOREIGN KEY
(
  LANGUAGE_ID 
)
REFERENCES BOOK_LANGUAGE
(
  LANGUAGE_ID 
)
ENABLE;

ALTER TABLE BOOK
ADD CONSTRAINT FK_BOOK_PUB FOREIGN KEY
(
  PUBLISHER_ID 
)
REFERENCES PUBLISHER
(
  PUBLISHER_ID 
)
ENABLE;

--BOOK_AUTHOR Table---------------------------------------------------------------------------------------------------------------
CREATE TABLE BOOK_AUTHOR 
(
  BOOK_ID NUMBER NOT NULL 
, AUTHOR_ID NUMBER NOT NULL 
, CONSTRAINT PK_BOOKAUTHOR PRIMARY KEY 
  (
    BOOK_ID 
  , AUTHOR_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_BOOKAUTHOR ON BOOK_AUTHOR (BOOK_ID ASC, AUTHOR_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE BOOK_AUTHOR
ADD CONSTRAINT FK_BA_AUTHOR FOREIGN KEY
(
  AUTHOR_ID 
)
REFERENCES AUTHOR
(
  AUTHOR_ID 
)
ENABLE;

ALTER TABLE BOOK_AUTHOR
ADD CONSTRAINT FK_BA_BOOK FOREIGN KEY
(
  BOOK_ID 
)
REFERENCES BOOK
(
  BOOK_ID 
)
ENABLE;

--BOOK_LANGUAGE Table---------------------------------------------------------------------------------------------------------------
CREATE TABLE COUNTRY 
(
  COUNTRY_ID NUMBER NOT NULL 
, COUNTRY_NAME VARCHAR2(200 BYTE) 
, CONSTRAINT PK_COUNTRY PRIMARY KEY 
  (
    COUNTRY_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_COUNTRY ON COUNTRY (COUNTRY_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

--COUNTRY Table---------------------------------------------------------------------------------------------------------------
CREATE TABLE COUNTRY 
(
  COUNTRY_ID NUMBER NOT NULL 
, COUNTRY_NAME VARCHAR2(200 BYTE) 
, CONSTRAINT PK_COUNTRY PRIMARY KEY 
  (
    COUNTRY_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_COUNTRY ON COUNTRY (COUNTRY_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

--CUST_ORDER Table---------------------------------------------------------------------------------------------------------------
CREATE TABLE CUST_ORDER 
(
  ORDER_ID NUMBER NOT NULL 
, ORDER_DATE DATE 
, CUSTOMER_ID NUMBER 
, SHIPPING_METHOD_ID NUMBER 
, DEST_ADDRESS_ID NUMBER 
, CONSTRAINT PK_CUSTORDER PRIMARY KEY 
  (
    ORDER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CUSTORDER ON CUST_ORDER (ORDER_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE CUST_ORDER
ADD CONSTRAINT FK_ORDER_ADDR FOREIGN KEY
(
  DEST_ADDRESS_ID 
)
REFERENCES ADDRESS
(
  ADDRESS_ID 
)
ENABLE;

ALTER TABLE CUST_ORDER
ADD CONSTRAINT FK_ORDER_CUST FOREIGN KEY
(
  CUSTOMER_ID 
)
REFERENCES CUSTOMER
(
  CUSTOMER_ID 
)
ENABLE;

ALTER TABLE CUST_ORDER
ADD CONSTRAINT FK_ORDER_SHIP FOREIGN KEY
(
  SHIPPING_METHOD_ID 
)
REFERENCES SHIPPING_METHOD
(
  METHOD_ID 
)
ENABLE;

--CUSTOMER Table---------------------------------------------------------------------------------------------------------------
CREATE TABLE CUSTOMER 
(
  CUSTOMER_ID NUMBER NOT NULL 
, FIRST_NAME VARCHAR2(200 BYTE) 
, LAST_NAME VARCHAR2(200 BYTE) 
, EMAIL VARCHAR2(350 BYTE) 
, CONSTRAINT PK_CUSTOMER PRIMARY KEY 
  (
    CUSTOMER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CUSTOMER ON CUSTOMER (CUSTOMER_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;
--CUSTOMER_ADDRESS Table---------------------------------------------------------------------------------------------------------------

CREATE TABLE CUSTOMER_ADDRESS 
(
  CUSTOMER_ID NUMBER NOT NULL 
, ADDRESS_ID NUMBER NOT NULL 
, STATUS_ID NUMBER 
, CONSTRAINT PK_CUSTADDR PRIMARY KEY 
  (
    CUSTOMER_ID 
  , ADDRESS_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CUSTADDR ON CUSTOMER_ADDRESS (CUSTOMER_ID ASC, ADDRESS_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE CUSTOMER_ADDRESS
ADD CONSTRAINT FK_CA_ADDR FOREIGN KEY
(
  ADDRESS_ID 
)
REFERENCES ADDRESS
(
  ADDRESS_ID 
)
ENABLE;

ALTER TABLE CUSTOMER_ADDRESS
ADD CONSTRAINT FK_CA_CUST FOREIGN KEY
(
  CUSTOMER_ID 
)
REFERENCES CUSTOMER
(
  CUSTOMER_ID 
)
ENABLE;

ALTER TABLE CUSTOMER_ADDRESS
ADD CONSTRAINT FK_CUST_ADDR FOREIGN KEY
(
  STATUS_ID 
)
REFERENCES ADDRESS_STATUS
(
  STATUS_ID 
)
ENABLE;
--ORDER_HISTORY Table---------------------------------------------------------------------------------------------------------------

CREATE TABLE ORDER_HISTORY 
(
  HISTORY_ID NUMBER NOT NULL 
, ORDER_ID NUMBER 
, STATUS_ID NUMBER 
, STATUS_DATE DATE 
, CONSTRAINT PK_ORDERHIST PRIMARY KEY 
  (
    HISTORY_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_ORDERHIST ON ORDER_HISTORY (HISTORY_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE ORDER_HISTORY
ADD CONSTRAINT FK_OH_ORDER FOREIGN KEY
(
  ORDER_ID 
)
REFERENCES CUST_ORDER
(
  ORDER_ID 
)
ENABLE;

ALTER TABLE ORDER_HISTORY
ADD CONSTRAINT FK_OH_STATUS FOREIGN KEY
(
  STATUS_ID 
)
REFERENCES ORDER_STATUS
(
  STATUS_ID 
)
ENABLE;
--ORDER_LINE Table---------------------------------------------------------------------------------------------------------------
CREATE TABLE ORDER_LINE 
(
  LINE_ID NUMBER NOT NULL 
, ORDER_ID NUMBER 
, BOOK_ID NUMBER 
, PRICE NUMBER(5, 2) 
, CONSTRAINT PK_ORDERLINE PRIMARY KEY 
  (
    LINE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_ORDERLINE ON ORDER_LINE (LINE_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE ORDER_LINE
ADD CONSTRAINT FK_OL_BOOK FOREIGN KEY
(
  BOOK_ID 
)
REFERENCES BOOK
(
  BOOK_ID 
)
ENABLE;

ALTER TABLE ORDER_LINE
ADD CONSTRAINT FK_OL_ORDER FOREIGN KEY
(
  ORDER_ID 
)
REFERENCES CUST_ORDER
(
  ORDER_ID 
)
ENABLE;
--OREDER_STATUS Table---------------------------------------------------------------------------------------------------------------
CREATE TABLE ORDER_STATUS 
(
  STATUS_ID NUMBER NOT NULL 
, STATUS_VALUE VARCHAR2(20 BYTE) 
, CONSTRAINT PK_ORDERSTATUS PRIMARY KEY 
  (
    STATUS_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_ORDERSTATUS ON ORDER_STATUS (STATUS_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;
--PUBLISHER Table---------------------------------------------------------------------------------------------------------------

CREATE TABLE PUBLISHER 
(
  PUBLISHER_ID NUMBER NOT NULL 
, PUBLISHER_NAME VARCHAR2(400 BYTE) 
, CONSTRAINT PK_PUBLISHER PRIMARY KEY 
  (
    PUBLISHER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_PUBLISHER ON PUBLISHER (PUBLISHER_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

--SHIPPING_METHOD Table---------------------------------------------------------------------------------------------------------------
CREATE TABLE SHIPPING_METHOD 
(
  METHOD_ID NUMBER NOT NULL 
, METHOD_NAME VARCHAR2(100 BYTE) 
, COST NUMBER(6, 2) 
, CONSTRAINT PK_SHIPMETHOD PRIMARY KEY 
  (
    METHOD_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_SHIPMETHOD ON SHIPPING_METHOD (METHOD_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;
--USERS Table---------------------------------------------------------------------------------------------------------------
CREATE TABLE USERS 
(
  USER_NAME VARCHAR2(20 BYTE) NOT NULL 
, PASSWORD NUMBER(*, 0) NOT NULL 
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    USER_NAME 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX USERS_PK ON USERS (USER_NAME ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;



